openapi: 3.0.1
info:
  description: Easily and directly detect and block bot activity.
  title: botapi
  version: v1
servers:
- url: https://api.cloudmersive.com/
security:
- Apikey: []
paths:
  /bot/captcha/image/generate:
    post:
      parameters:
      - description: Number of characters to request that the user enter; must be
          2 or more
        in: header
        name: Characters
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ImageCaptchaGenerateResult'
            application/json:
              schema:
                $ref: '#/components/schemas/ImageCaptchaGenerateResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ImageCaptchaGenerateResult'
          description: OK
      summary: Create an image CAPTCHA
      tags:
      - Captcha
  /bot/captcha/image/validate:
    post:
      parameters:
      - description: The ID of the CAPTCHA (this is returned from the CAPTCHA generate
          API)
        in: header
        name: CaptchaID
        schema:
          type: string
      - description: The challenge response input text received from the user to validate
          if they are a person or bot
        in: header
        name: ChallengeResponse
        schema:
          type: string
      - description: "The amount of time in milliseconds to allow the user to respond;\
          \ if the response occurs more than this amount of time, in milliseconds,\
          \ after the CAPTCHA was created, the answer will be considered invalid even\
          \ if it is correct"
        in: header
        name: UserTimeoutMilliseconds
        schema:
          format: int32
          type: integer
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ImageCaptchaValidateResult'
            application/json:
              schema:
                $ref: '#/components/schemas/ImageCaptchaValidateResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ImageCaptchaValidateResult'
          description: OK
      summary: Validate a CAPTCHA response from the user
      tags:
      - Captcha
components:
  schemas:
    ImageCaptchaGenerateResult:
      additionalProperties: false
      example:
        imageCaptchaPng: imageCaptchaPng
        captchaID: captchaID
        successful: true
      properties:
        successful:
          type: boolean
        captchaID:
          type: string
        imageCaptchaPng:
          format: byte
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
      type: object
    ImageCaptchaValidateResult:
      additionalProperties: false
      example:
        cleanResult: true
      properties:
        cleanResult:
          type: boolean
      type: object
  securitySchemes:
    Apikey:
      description: Apikey
      in: header
      name: Apikey
      type: apiKey
x-original-swagger-version: "2.0"

